[features]
seeds = false
skip-lint = false

[programs.localnet]
dtt = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[programs.devnet]
dtt = "8co2yTf2PEXtsNpcBACJgNQHPorUpe2FYHLKHLQphwfH"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/marche/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
